version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-246-100-246.eu-west-1.compute.amazonaws.com
            database: d6c0aspbcsmbi
            user: vaodngxtdzqfov
            password: 5f7ce17ae11af8de309318baea5b4b22ac51ba8678254d9876e24d08c8f3fe5e
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true